### ISSUE TITLE
Computed Values

### ISSUE THREAD

**Issue by tfrank64** [Skyvive/JsonObject#2]
Something I found that would be really useful is way to compute properties immediately after you receive the JSON. Currently I just call a method after I create a `JsonObject`, but I'm thinking I could also use the `didSet` feature in Swift on a specific property, like so:

```
var time: Double = 0 {
    didSet {
        refreshedDate = NSDate(timeIntervalSince1970: time.calculateTimestamp())
    }
}
```

Do you imagine there is a better, more built-in way to accomplish the task of modifying JSON data on `JsonObject` creation? This could be as simple as overriding an init method, but not sure how that would work within this library.
Thanks!

**Comment by bradhilton** [comment]
Overriding the init method and calling the super's implementation should work just fine:

``` swift
required init?(dictionary: NSDictionary, shouldValidate: Bool) {
    super.init(dictionary: dictionary, shouldValidate: shouldValidate)
    self.refreshedDate = NSDate(timeIntervalSince1970: self.time.calculateTimestamp())
}
```

If `refreshedDate` is dependent on `time` you could also use a computed property instead:

``` swift
var refreshedDate: NSDate = {
    return NSDate(timeIntervalSince1970: time.calculateTimestamp())
}
```

**Comment by tfrank64** [comment]
Thanks for that comment, both look like great solutions.

I can add those 2 options in your README if you agree they would be helpful?

**Comment by tfrank64** [comment]
I actually couldn't get it to work properly using the 2 suggestions above, what did work was this:

```
var refreshedDate: NSDate {
    return NSDate(timeIntervalSince1970: self.time.calculateTimestamp())
}
```

Taking away the equals sign is all I changed for that one, while the other method, overriding the init method, must not have gotten called in the right order.

**Comment by bradhilton** [comment]
You're right, the equals sign is not needed. I was able to get the init function to work, but I think that the computed property is more elegant. I don't know if this should be included in the readme, since these solutions are just using native swift features. I'm going to think more about object initialization and if there's a specific way we should address this in JsonObject. 

I have also been working on a more flexible library, [JsonSerializer](https://github.com/Skyvive/JsonSerializer) which has additional features (including custom key mapping) and let's you set the properties of any NSObject subclass from a dictionary. I haven't had a chance to document it yet, but if you want more flexibility at initialization it might be worth a look.

**Comment by tfrank64** [comment]
Sounds good to me, it's your call. I will continue to use the computed property method you mentioned. 
Thanks for looking to improve JsonObject.

Nice, I look forward to the completion of your next project!
